import { NextResponse } from "next/server";

const APP_URL = process.env.NEXT_PUBLIC_APP_URL || "https://www.mob.ar";

/**
 * Manual sitemap index that references the 4 sub-sitemaps generated by
 * app/sitemap.ts via generateSitemaps().
 *
 * Next.js does not reliably auto-generate a sitemap index, so we serve
 * one explicitly at /sitemap-index.xml.
 *
 * Sub-sitemaps:
 *   /sitemap/0.xml – static pages + blog
 *   /sitemap/1.xml – property detail pages
 *   /sitemap/2.xml – location pages
 *   /sitemap/3.xml – programmatic SEO pages
 */
export async function GET() {
  const ids = [0, 1, 2, 3];

  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...ids.map(
      (id) =>
        `  <sitemap>\n    <loc>${APP_URL}/sitemap/${id}.xml</loc>\n  </sitemap>`
    ),
    "</sitemapindex>",
  ].join("\n");

  return new NextResponse(xml, {
    headers: {
      "Content-Type": "application/xml",
      "Cache-Control": "public, max-age=3600, s-maxage=3600",
    },
  });
}
